services:
  - type: web
    name: ddi-predict
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
